apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-workspace-test
spec:
  params:
    - name: workspace-name
      type: string
    - name: template-name
      type: string
    - name: coder-url
      type: string
    - name: coder-token-secret
      type: string
  steps:
    - name: delete-coder-workspace
      image: ghcr.io/sprint-cloud/pipeline-worker:82dc994798d9843640f67c1ac3384072757a3124
      onError: continue
      env:
        - name: CODER_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.coder-token-secret)
              key: token
      script: |
          coder --token $CODER_TOKEN --url $(params.coder-url) delete --yes "$(params.workspace-name)"
    - name: delete-coder-template
      image: ghcr.io/sprint-cloud/pipeline-worker:82dc994798d9843640f67c1ac3384072757a3124
      onError: continue
      env:
        - name: CODER_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.coder-token-secret)
              key: token
      script: |
          coder --token $CODER_TOKEN --url $(params.coder-url) template delete --yes $(params.template-name)
    