apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: coder-release-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: template-name
      type: string
    - name: coder-url
      type: string
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: check-existence-template
        taskRef: 
          name: check-existence-template
        params:
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: "$(params.coder-url)"
          - name: coder-token-secret
            value: coder-prod-auth
      - name: upload-coder-template
        taskRef: 
          name: create-coder-template
        runAfter:
            - fetch-repository
          - input: "$(tasks.check-existence-template.results.template-exists)"
            operator: in
            values: ["false"] 
        workspaces:
          - name: template
            workspace: source
        params:
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: $(params.coder-url)
          - name: coder-token-secret
            value: coder-prod-auth
      - name: update-coder-template
        taskRef: 
          name: update-coder-template
        runAfter:
            - fetch-repository
        when:
          - input: "$(tasks.check-existence-template.results.template-exists)"
            operator: in
            values: ["true"] 
        workspaces:
          - name: template
            workspace: source
        params:
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: $(params.coder-url)
          - name: coder-token-secret
            value: coder-prod-auth
      
        


    
                
