apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: coder-testing-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: template-name
      type: string
    - name: workspace-name
      type: string
    - name: coder-url
      type: string
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: upload-coder-template
        taskRef: 
          name: create-coder-template
        runAfter:
            - fetch-repository
        workspaces:
          - name: template
            workspace: source
        params:
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: $(params.coder-url)
          - name: coder-token-secret
            value: coder-testing-auth
      - name: test-coder-workspace
        taskRef: 
          name: create-coder-workspace
        runAfter:
          - upload-coder-template
        params:
          - name: workspace-name
            value: $(params.workspace-name)
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: $(params.coder-url)
          - name: coder-token-secret
            value: coder-testing-auth
  finally:
      - name: cleanup
        taskRef: 
          name: cleanup-workspace-test
        params:
          - name: workspace-name
            value: $(params.workspace-name)
          - name: template-name
            value: $(params.template-name)
          - name: coder-url
            value: $(params.coder-url)
          - name: coder-token-secret
            value: coder-testing-auth


    
                
