apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: coder-testing-pipeline
spec:
  params:
    - name: repo_url
      type: string
    - name: revision
      type: string
    - name: coder-helm-version
      type: string
    - name: template-name
      type: string
    - name: testing-namespace
      type: string
    - name: testing-tag
      type: string
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: testing-coder-template
        workspaces:
          - name: source
        params:
          - name: namespace
            value: $(params.testing-namespace)
          - name: tag
            value: $(params.testing-tag)
        taskSpec:
          params:
            - name: namespace
              type: string
            - name: tag
              type: string
          steps:
            - name: create-vcluster
              workingDir: $(workspaces.source.path)
              image: ghcr.io/sprint-cloud/pipeline-worker:66567fc4a0d65b4e37f03282c6f13988445d52cc
              script: |
                  vcluster create workspace-test-$(params.tag) --namespace $(params.namespace)
                  sleep 15
                  vcluster delete workspace-test-$(params.tag) --namespace $(params.namespace)

    
                
