apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: coder-testing-pipeline
spec:
  params:
    - name: repo_url
    - name: revision
    - name: coder-version
    - name: template-name
  workspaces:
    - name: source
    - name: basic-auth
  tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)