FROM ghcr.io/sprint-cloud/workspace-base
LABEL org.opencontainers.image.source https://github.com/sprint-cloud/workspace-template

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv

USER sprinter

